// <auto-generated />
using System;
using AccountService.Infrastructure.Read;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountService.Infrastructure.Read.Migrations
{
    [DbContext(typeof(AccountDbContextRead))]
    [Migration("20250616151350_AddTableShift")]
    partial class AddTableShift
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountService.Domain.Entity.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AboutLawyer")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("AccountDob")
                        .HasColumnType("date");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AccountFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("AccountGender")
                        .HasColumnType("integer");

                    b.Property<string>("AccountImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AccountPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AccountPhone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("AccountRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("AccountTicketRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("AccountUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AccountId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("AccountService.Domain.Entity.ForgotPassword", b =>
                {
                    b.Property<Guid>("ForgotPasswordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("ForgotPasswordId");

                    b.HasIndex("AccountId");

                    b.ToTable("ForgotPassword", (string)null);
                });

            modelBuilder.Entity("AccountService.Domain.Entity.LawyerDayOffSchedule", b =>
                {
                    b.Property<Guid>("LawyerDayOffScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LawyerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("OffDay")
                        .HasColumnType("date");

                    b.HasKey("LawyerDayOffScheduleId");

                    b.HasIndex("LawyerId");

                    b.ToTable("LawyerDayOffSchedule", (string)null);
                });

            modelBuilder.Entity("AccountService.Domain.Entity.LawyerSpecificService", b =>
                {
                    b.Property<Guid>("LawyerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<double>("PricePerHour")
                        .HasColumnType("double precision");

                    b.HasKey("LawyerId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("LawyerSpecificService", (string)null);
                });

            modelBuilder.Entity("AccountService.Domain.Entity.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ServiceId");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("AccountService.Domain.Entity.Shift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("ShiftId");

                    b.ToTable("Shift", (string)null);
                });

            modelBuilder.Entity("AccountService.Domain.Entity.SpecificLawyerDayOffSchedule", b =>
                {
                    b.Property<Guid>("LawyerDayOffScheduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LawyerDayOffScheduleId", "ShiftId");

                    b.HasIndex("ShiftId");

                    b.ToTable("SpecificLawyerDayOffSchedule", (string)null);
                });

            modelBuilder.Entity("AccountService.Domain.Entity.ForgotPassword", b =>
                {
                    b.HasOne("AccountService.Domain.Entity.Account", "Account")
                        .WithMany("ForgotPasswords")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ForgotPassword_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AccountService.Domain.Entity.LawyerDayOffSchedule", b =>
                {
                    b.HasOne("AccountService.Domain.Entity.Account", "Lawyer")
                        .WithMany("LawyerDayOffSchedules")
                        .HasForeignKey("LawyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LawyerDayOffSchedule_Account");

                    b.Navigation("Lawyer");
                });

            modelBuilder.Entity("AccountService.Domain.Entity.LawyerSpecificService", b =>
                {
                    b.HasOne("AccountService.Domain.Entity.Account", "Account")
                        .WithMany("LawyerSpecificServices")
                        .HasForeignKey("LawyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LawyerSpecificService_Account");

                    b.HasOne("AccountService.Domain.Entity.Service", "Service")
                        .WithMany("LawyerSpecificServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LawyerSpecificService_Service");

                    b.Navigation("Account");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AccountService.Domain.Entity.SpecificLawyerDayOffSchedule", b =>
                {
                    b.HasOne("AccountService.Domain.Entity.LawyerDayOffSchedule", "LawyerDayOffSchedule")
                        .WithMany("SpecificLawyerDayOffSchedules")
                        .HasForeignKey("LawyerDayOffScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SpecificLawyerDayOffSchedule_LawyerDayOffSchedule");

                    b.HasOne("AccountService.Domain.Entity.Shift", "Shift")
                        .WithMany("SpecificLawyerDayOffSchedules")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SpecificLawyerDayOffSchedule_Shift");

                    b.Navigation("LawyerDayOffSchedule");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("AccountService.Domain.Entity.Account", b =>
                {
                    b.Navigation("ForgotPasswords");

                    b.Navigation("LawyerDayOffSchedules");

                    b.Navigation("LawyerSpecificServices");
                });

            modelBuilder.Entity("AccountService.Domain.Entity.LawyerDayOffSchedule", b =>
                {
                    b.Navigation("SpecificLawyerDayOffSchedules");
                });

            modelBuilder.Entity("AccountService.Domain.Entity.Service", b =>
                {
                    b.Navigation("LawyerSpecificServices");
                });

            modelBuilder.Entity("AccountService.Domain.Entity.Shift", b =>
                {
                    b.Navigation("SpecificLawyerDayOffSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
